trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    git push --prune https://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@github.com/worc4021/mexIpopt.git \
        +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
  displayName: 'Copy to Github'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
