BINROOT = '/Users/Manuel/Documents/Development/binaries';
MEXBUILDINGBLOCKS = '/Users/Manuel/Documents/Development/MexBuildingBlocks';


mex('-output','ipopt',...
    ['-I',fullfile(BINROOT,'include','coin-or')],...
    ['-L',fullfile(BINROOT,'lib')],...
    ['-I',MEXBUILDINGBLOCKS],...
    'CC=/usr/bin/xcrun  gcc',...
    'CXX=/usr/bin/xcrun  g++',...
    'LD=/usr/bin/xcrun  gcc',...
    'LDXX=/usr/bin/xcrun  g++',...
    '-lipopt',...
    'main.cpp')